name: SonarQube Code Quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Tests
        run: |
          python -m compileall .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
